[package]
name = "janusmap"
version = "0.1.0"
license = "MIT"
edition = "2024"
repository = "https://github.com/someotherself/janusmap"
description = "Experiment into concurrent hashmaps"
readme = "README.md"
keywords = ["concurrent", "hashmap"]
categories = ["concurrency", "algorithms", "data-structures"]

[dependencies]
crossbeam = "0.8.4"
parking_lot_core = "0.9.12"
seize = "0.5.1"
